--- 
name: Test.php
version: 0.01
abstract: TAP test framework for PHP with a L<Test::More>-like interface
author: "\xC3\x86var Arnfj\xC3\xB6r\xC3\xB0 Bjarmason <avar@cpan.org>"
distribution_type: module
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3

no_index: 
  directory: 
    - t
tests: t/*.t
generated_by: "\xC3\x86var Arnfj\xC3\xB6r\xC3\xB0 Bjarmason <avar@cpan.org>"